#Set trigger to none so that the pipeline can be manually triggered
trigger: none

# Define variable names and groups here
variables:
- group: azure-blob

# The agent pools where the jobs will run
pool:
  name: 'Pool-Linux'

stages:

# Define Stage
- stage: Build
  displayName: 'Build and Deploy'
  jobs:

  # Define Job
  - job: AddSecrets
    displayName: 'Add Secrets to Key Vault'

    # Define steps in the job
    steps:
    
    # This task is used to add keys to azure key vault via azure cli command
    - task: AzureCLI@2
      displayName: 'Set Key Vault Secret'
      inputs:
        azureSubscription: 'MLOPS-DEV'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          # Use the Azure CLI to set a secret in the specified Key Vault
          az keyvault secret set --name "AZURE-CONNECTION-STRING" --vault-name "kv-shs-az-eus-mlops-npd" --value "$(AZURE-CONNECTION-STRING)"
      env:
        AZURE_CONNECTION_STRING: $(AZURE-CONNECTION-STRING)